const GET_NAME = 'GET_NAME'
const GET_DIANPU ='GET_DIANPU'
const GET_CITY='GET_CITY'
const SHOW_CITY='SHOW_CITY'
const HIDEN_CITY='HIDEN_CITY'
const GET_CLASSIFYAREA='GET_CLASSIFYAREA'
const GET_PARTAREA='GET_PARTAREA'
const GET_RESTAURANT='GET_RESTAURANT'
export default {
  GET_NAME,
  GET_DIANPU,
  GET_CITY,
  SHOW_CITY,
  HIDEN_CITY,
  GET_CLASSIFYAREA,
  GET_RESTAURANT
}
