const GET_CITY='GET_CITY'
const SHOW_CITY='SHOW_CITY'
const HIDEN_CITY='HIDEN_CITY'
const GET_CLASSIFYAREA='GET_CLASSIFYAREA'
const GET_RESTAURANT='GET_RESTAURANT'
const GET_KTV='GET_KTV'
export const GET_NAME = 'GET_NAME'
export const GET_GROUPBUYING='GET_GROUPBUYING'
export const GET_DIANPU ='GET_DIANPU'
export default {
  GET_NAME,
  GET_CITY,
  SHOW_CITY,
  HIDEN_CITY,
  GET_CLASSIFYAREA,
  GET_RESTAURANT,
  GET_KTV,
}
